<?php
echo $this->render('common/header.phtml');
?>
<?php

echo $this->render('common/menu.phtml');
?>
<?php

$table = Zend_Registry::get('dbtable')->goods;
$details = $this->details;
?>
<script type="text/javascript"
	src="<?php echo APPLICATION_PUBLIC_PATH; ?>/js/jquery.imgresize.js"></script>
<script type="text/javascript"
	src="<?php echo APPLICATION_PUBLIC_PATH; ?>/js/goods.js"></script>
<div id="body" class="fm960 clearfix">
	<div id="content_top"></div>
	<div class="piece piece_w960 piece_note">
		<div class="piece_hd"></div>
		<div class="piece_bd clearfix">
			<div class="fl" id="content_body">
				<!-- 显示图片 begin  -->
				<div class="show_body ">
					<input type="hidden" value="1epg4pg" class="tid_view"> <input
						type="hidden" value="1" class="show_history_btn">
					<div tid="1epg4pg" class="img_show " type="goods" iid="18jayy0">
						<a rel="nofollow" target="_blank"
							href="<?php echo $details[$table->url];?>"
							class="show_big qplus_link"> <img
							title="<?php echo $details[$table->name];?>"
							alt="<?php echo $details[$table->name];?>"
							src="<?php echo $details[$table->picUrl];?>">
						</a> <a href="javascript:;" class="add_to_album_btn"
							style="display: none;"></a>
					</div>
					<!-- 下方小图(兼容老的推) begin  -->
				</div>
				<!--    <a href="#test" class="anchor">测试锚点</a>
<a name="test" ></a>-->
				<!-- 显示图片 end  -->
				<!-- 同类产品 end  -->
			</div>
			<div class="fr" id="right_side">
				<div class="fav_wrap_content clearfix">
					<div class="favorite ">
						<a id="likeButton" class="favaImg" href="javascript:;">喜欢</a>
						<div class="favDiv fl">
							<a target="_blank" class="favCount"><?php echo $details[$table->like];?></a>
							<i></i>
						</div>
					</div>
				</div>
				<img style="display: none"
					src="/mbs.htm?timestamp=1368856417&amp;from=note_no_tongkuan">
				<div class="body_info" tuanid="1178gs" tid="1epg4pg" gid="18jayy0">
					<div class="goods_link">
						<div class="shop_link_box">
							<a href="<?php echo $details[$table->url];?>"
								title="<?php echo $details[$table->name];?>" target="_blank"
								class="shop_link" rel="nofollow"><?php echo $details[$table->name];?></a>
						</div>
						<p class="price">
							<a href="<?php echo $details[$table->url];?>" target="_blank">¥<?php echo $details[$table->price];?></a>
						</p>
						<a target="_blank" href="<?php echo $details[$table->url];?>"
							class="buy_link" rel="nofollow">去购买</a>
					</div>
				</div>
				<!-- 纯图片时显示用户信息 begin-->
				<div class="first_share">
				<?php $userinfo = $this->getUserInfo($details[$table->userid]);?>
					<h2 class="title">分享的可爱会员</h2>
					<div class="share_user_info clearfix">
						<div class="pic fl">
							<a target="_blank" href="<?php echo APPLICATION_ACTION_PATH; ?>/user/profile/uid/<?php echo $userinfo['id']?>"> <img width="49px"
								height="49px"
								src="<?php echo APPLICATION_PUBLIC_PATH . $userinfo['avatar'];?>"
								alt="<?php echo $userinfo['username'];?>"
								class="icard avt fl r3">
							</a>
						</div>
						<div class="content">
							<a target="_blank" href="<?php echo APPLICATION_ACTION_PATH; ?>/user/profile/uid/<?php echo $userinfo['id']?>" class="icard avt uname"><?php echo $userinfo['username'];?></a>
							<span class="get_fav">获得<?php echo $details[$table->like]; ?>个喜欢</span>
							<p class="tweet_from">
								<span></span>
							</p>
							<p class="share_content">
								<span class="t"><?php echo date('Y年m月d日 H:i:s', strtotime($details[$table->ctime])); ?></span>
							</p>
						</div>
					</div>
				</div>
				<!-- 第一个分享的人 end -->

				<!-- 评论框 begin -->
				<div class="note_comment_wrap note_content" id="note_1epg4pg"
					data="{&quot;is_public&quot;:&quot;p&quot;,&quot;type&quot;: &quot;goods&quot;, &quot;itemInfoId&quot;: &quot;1198ww8&quot;,&quot;ff&quot;:&quot;%2Fshopping%2F&quot;}">
					<div class="pub_area">
						<div class="pub_area_bd">
							<textarea id="pub_content" class="pub_txt"
								placeholder="你也可以顺便说点什么 O(∩_∩)O"></textarea>
						</div>
						<div class="pub_area_ft">
							<a href="javascript:;" class="gray_btn submit r3 fr"
								id="pub_submit"><span class="s">确定</span></a> <input
								type="hidden" id="goodsId"
								value="<?php echo $details[$table->id]; ?>" /> <input
								type="hidden" id="goodsAuthor"
								value="<?php echo $details[$table->userid]; ?>" />
						</div>
					</div>
					<!-- 评论框 end -->
					<!-- 评论列表 begin -->
					<div class="note_comment">
						<ul id="note_comment_list" class="c_l rb5">
						<?php
    $comments = $this->comments;
    foreach ($comments as $comment) {
        $commentUserInfo = $this->getUserInfo($comment['author']);
        ?>
							<li class="c_f" uid="" tid="1eq7pq8"><a href="<?php echo APPLICATION_ACTION_PATH; ?>/user/profile/uid/<?php echo $commentUserInfo['id']?>"
								target="_blank"><img
									src="<?php echo APPLICATION_PUBLIC_PATH . $commentUserInfo['avatar']; ?>"
									class="avt icard"
									alt="<?php echo $commentUserInfo['username']?>"></a>
								<p class="sms">
									<a href="<?php echo APPLICATION_ACTION_PATH; ?>/user/profile/uid/<?php echo $commentUserInfo['id']?>" target="_blank" class="n icard"><?php echo $commentUserInfo['username']?></a>
								</p>
								<p class="sms">
									<?php echo $comment['content']?><span>&nbsp;&nbsp;&nbsp;<?php echo date('Y-m-d H:i:s', strtotime($comment['ctime'])); ?></span>
								</p></li>
						<?php
    }
    ?>
						</ul>
					</div>
					<!-- 评论列表 end -->
				</div>
			</div>
		</div>
		<div class="piece_ft"></div>
	</div>
	<div id="content_bottom">
		<div class="mt25 fm960"
			style="font-size: 30px; color: #690; font-weight: bold;">你可能还喜欢</div>
			<?php
echo $this->render('common/block.phtml');
?>
			<div></div>
	</div>
	<script type="text/javascript">
    $('.img_show').find('img').imgresize({width:400});
    </script>
<?php
echo $this->render('common/footer.phtml');
?>