<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="content1">
		<div id="cat">
			<img src="<?php echo APPLICATION_PUBLIC_PATH; ?>/images/cat.png">
		</div>
		<div id="list">
			<div class="block">
			<span class="st">送给谁</span>
			<ul>
			<li class="mulu">送女友</li>
			<li class="mulu">送男友</li>
			<li class="mulu">送长辈</li>
			<li class="mulu">送领导</li>
			<li class="mulu">送女生</li>
			<li class="mulu">送男生</li>
			<li class="mulu">送客户</li>
			</ul>
			</div><div class="block">
			<span class="st">场合</span>
			<ul>
			<li class="mulu">生日</li>
			<li class="mulu">结婚</li>
			<li class="mulu">纪念日</li>
			<li class="mulu">圣诞</li>
			<li class="mulu">约会</li>
			<li class="mulu">晋升</li>
			<li class="mulu">乔迁之喜</li>
			<li class="mulu">感谢</li>
			<li class="mulu">拜访</li>
			<li class="mulu">道歉</li>
			<li class="mulu">探病</li>
			<li class="mulu">教师节</li>
			</ul>
			</div>
			<div class="block">
			<span class="st">收礼爱好</span>
			<ul>
			<li class="mulu">爱浪漫</li>
			<li class="mulu">爱喝酒</li>
			<li class="mulu">爱旅游</li>
			<li class="mulu">爱艺术</li>
			<li class="mulu">爱养生</li>
			<li class="mulu">爱运动</li>
			<li class="mulu">爱品茶/咖啡</li>
			<li class="mulu">居家实用型</li>
			<li class="mulu">爱美/爱打扮</li>
			<li class="mulu">爱毛绒公仔</li>
			<li class="mulu">爱创意</li>
			</ul>
			</div>
		</div>			
	</div>
		<div class="goods_filter">
			<div class="fl">
				<div class="filter_module">
					<b class="title">排序方式</b>
					<a href="#" class="selector">最新分享</a>
					<a href="#" class="selector ">最受欢迎</a>
				</div>
			</div>
		</div>
	<?php
	echo $this->render('common/block.phtml');
	?>
	<div id="footer">
	</div>
</div>
<?php
echo $this->render('common/footer.phtml');
?>
