<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title><?php echo $this->title; ?></title>
        <meta content="text/html; charset=utf-8" http-equiv="content-type" />
        <link type="text/css" rel="stylesheet" href="<?php echo APPLICATION_PUBLIC_PATH;?>/theme/backadmin.css" />
        <script type="text/javascript" src="<?php echo APPLICATION_PUBLIC_PATH; ?>/js/jquery-1.8.3.min.js"></script>
        <script type="text/javascript" src="<?php echo APPLICATION_PUBLIC_PATH;?>/ckeditor/ckeditor.js"></script>
    </head>
    <script type="text/javascript">
    $(function(){
        $('#addPic').click(function(){
            var id = $('#countRow').val();
            var currid = parseInt(id) + 1;
            $('#countRow').val(currid);
            var arr = [];
            arr.push('<tr><td>');
            arr.push(id + '</td><td><input id="title');
            arr.push(id + '" type="text" width="100%" name="title');
            arr.push(id + '" /></td><td><input id="description');
            arr.push(id + '" type="text" width="100%" name="description');
            arr.push(id + '" /></td><td><input id="detailUrl');
       		arr.push(id + '" type="text" width="100%" name="detailUrl');
            arr.push(id + '" /></td><td><input id="imageUrl');
            arr.push(id + '" type="text" width="100%" name="imageUrl');
            arr.push(id + '" /></td></tr>');
            var html = arr.join("");
            $('#sliderTable').append(html);
        });
    });
    </script>
    <body>
        <h1 class="title"><?php echo $this->title;?></h1>
        <div class="content">
            <p id="msg" style="color:red;font-size:18px;font-weight:bold;">
                <?php echo $this -> errormsg;?>
            </p>
            <form name="homepage" action="<?php echo APPLICATION_ACTION_PATH . "/manage/mod-homepage-slider";?>" method="post">
                <table width="900px" border="1px" cellspacing="0" id="sliderTable">
                    <tr>
                        <th colspan="5">首页图片轮转设置</th>
                    </tr>
                    <tr>
                        <th width="5%">编号</th>
                        <th width="10%">图片标题</th>
                        <th width="25%">图片描述</th>
                        <th width="30%">图片地址</th>
                        <th width="30%">点击图片跳转地址</th>
                    </tr>
                    <?php 
                    $slider = $this->slider;
                    $sliderTable = $this->sliderTable;
                    $count = 1;
                    foreach ($slider as $pic) {
                    ?>
                    <tr>
                        <td><?php echo $count; ?></td>
                        <td>
                        <input id="title<?php echo $count; ?>" type="text" width="100%" name="title<?php echo $count; ?>" value="<?php echo $pic[$sliderTable->title]; ?>" />
                        </td>
                        <td>
                        <input id="description<?php echo $count; ?>" type="text" width="100%" name="description<?php echo $count; ?>" value="<?php echo $pic[$sliderTable->description]; ?>" />
                        </td>
                        <td>
                        <input id="imageUrl<?php echo $count; ?>" type="text" width="100%" name="imageUrl<?php echo $count; ?>" value="<?php echo $pic[$sliderTable->imageUrl]; ?>" />
                        </td>
                        <td>
                        <input id="detailUrl<?php echo $count; ?>" type="text" width="100%" name="detailUrl<?php echo $count; ?>" value="<?php echo $pic[$sliderTable->detailUrl]; ?>" />
                        </td>
                    </tr>
                    <?php 
                        $count++;
                    }
                    ?>
                </table>
                <p>
                	<input id="countRow" type="hidden" value="<?php echo $count; ?>" />
                	<input id="addPic" type="button" value="添加一张图片" />
                    <input type="submit" value="Submit" />
                </p>
            </form>
        </div>
    </body>
</html>