<link rel="stylesheet" href="<?php echo APPLICATION_PUBLIC_PATH; ?>/css/block.css" />
<script src="<?php echo APPLICATION_PUBLIC_PATH;?>/js/block.js"
type="text/javascript"></script>
<input id="cateValue" type="hidden" value="" />
<input id="pageValue" type="hidden" value="1" />
<input id="useridValue" type="hidden" value="" />
<input id="orderValue" type="hidden" value="" />
<div id="main">
<div id="store"></div>
</div>