<link rel="stylesheet" href="<?php echo APPLICATION_PUBLIC_PATH; ?>/css/block.css" />
<input id="cateValue" type="hidden" value="" />
<input id="pageValue" type="hidden" value="1" />
<input id="useridValue" type="hidden" value="" />
<input id="usertypeValue" type="hidden" value="" />
<input id="orderValue" type="hidden" value="" />
<input id="keywordValue" type="hidden" value="<?php echo $this->keyword; ?>" />
<div id="main">
<div id="store"></div>
</div>