<div class="wrapper">
       <div id=left></div>
	<div id="top7" class="transparent_class">
    <div class="floating">
   	  <div class="imgbox">
    		<div class="heart">
             </div>
         	<div class="teaname"></div>
   		 </div>
    </div>
    
     <div class="floating"><div class="imgbox">
       <div class="heart"></div><div class="teaname"></div></div></div>
       
       <div class="floating"><div class="imgbox">
       <div class="heart">12</div><div class="teaname"></div></div></div>
       
        <div class="floating"><div class="imgbox">
       <div class="heart"></div><div class="teaname"></div></div></div>
       
        <div class="floating"><div class="imgbox">
       <div class="heart"></div><div class="teaname"></div></div></div>
       
        <div class="floating"><div class="imgbox">
       <div class="heart"></div><div class="teaname"></div></div></div>
       
        <div class="floating"><div class="imgbox">
       <div class="heart"></div><div class="teaname"></div></div></div>
<br clear="all" />
</div>
<div id=right></div>
</div>
<div id="footer"></div>
</body>
</html>