<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH;?>css/layout.css">
<title><?php echo $this->title;?></title>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/jquery.pagination.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/config.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/function.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/main.js"></script>
</head>
<body>
<div id="header">
  <div class="wrapper"> <a id="tea" href=""><img src="<?php echo PUBLIC_PATH;?>images/logo.png" /></a>
    <div id="menu"> <a id="nav_bar_home" target="_parent" href="<?php echo URL_PATH; ?>" ><span>Home</span></a> <a target="_parent" id="nav_bar_test"href="<?php echo URL_PATH . 'index/test'; ?>" ><span>Test</span></a> <a target="_parent"  id="nav_bar_shop" href="<?php echo URL_PATH . 'goods'; ?>" ><span>Shop</span></a> </div>
  </div>
</div>