<script type='text/javascript' src='<?php echo APPLICATION_PUBLIC_PATH; ?>/js/login.js'></script>
<div id="loginBox" class="login_box">
	<p class="login_close">
		<a id="loginClose" href="###">关闭</a>
	</p>
	<p class="login_title">
		您还没有登录，请先登录！
	</p>
	<p class="login_p">
		<label>用户名：</label>
		<input id="username" type="text">
	</p>
	<p class="login_p">
		<label>密&nbsp;&nbsp;码：</label>
		<input id="passwd" type="password">
	</p>
	<p class="login_btns">
    	<a id="loginButton" class="login_btn" href="###"></a>
    	<a class="login_btn2" target="_blank" href="http://i.10jqka.com.cn/register/index">立即注册</a>
    </p>
</div>
<div class="filter" style="display:none" id="filter"></div>