<div class="bg">
<div id="guide"><!--Guide -->
	<div id="guide-inner"><!--Inner -->
    	<div class="l">
			<div class="item-guide-top dropdown">
				<a id="link-logo-guide" href="<?php echo APPLICATION_ACTION_PATH; ?>/">Gift</a>
			</div>
			<div class="item-guide-top dropdown">
				<a class="item-channel-guide" href="<?php echo APPLICATION_ACTION_PATH; ?>/goods" target="选礼物">选礼物</a>
			</div>
			<div class="item-guide-top">
				<a class="item-channel-guide" href="<?php echo APPLICATION_ACTION_PATH; ?>/bbs" title="讨论吧">讨论吧</a>
			</div>
			<div class="item-guide-top">
				<a class="item-channel-guide" href="<?php echo APPLICATION_ACTION_PATH; ?>/user" title="自家乐园">自家乐园</a>
			</div>
		</div>
		<div class="r">
			<div id="share" class="item-guide-top"><div id="area-public-guide-top" class="item-guide-top"><a class="btn mini" onclick="" title="分享" href="<?php echo APPLICATION_ACTION_PATH?>/goods/share">分享</a></div></div>
			<div id="search-guide" class="item-guide-top"><!--Search -->
				<input id="input-search-guide" name="q" type="text" placeholder="搜索" autocomplete="off" x-webkit-speech=""><button id="btn-09252008595503867" class="btn-search" title="搜索" style="left: 136px; top: 9px;"><i class="icon icon-search">搜索</i></button><ul id="menu-09252008595503867" class="menu menu-search" style="left: 0px; top: 44px; min-width: 162px;"></ul>
			</div><!--Search -->
			<div id="login-guide" class="item-guide-top">
			<?php 
			if (empty($this->userinfo)) {
			?>
			<div id="area-public-guide-top" class="item-guide-top"><a class="btn info mini" id="loginBtn" title="帐号登录" href="###">登录</a><a class="btn success mini" onclick="javascript:$(this).call('reg');" title="帐号注册" href="<?php echo APPLICATION_ACTION_PATH?>/user/registration">注册</a></div>
			<?php
			} else {
				$userinfo = $this->userinfo;
			?>
			<input type="hidden" value="<?php echo $userinfo['id']; ?>"/><a href=""><?php echo $userinfo['username']; ?></a>
			<?php 
			}
			?>
			</div>
		</div>
		<span class="clearfix"></span>
    </div><!--Inner -->
</div>