<div class="main_hidden_test">
    <div id="sideshoppingcart"><br><br><br><br>Shopping cart<br>
    <div id="shoppingcartlist">
    </div>
    <div class="sideshoppingcartteanameqty">
    <div class="sideshoppingcartteaname"></div>
    <div class="sideshoppingcartqty"></div>
     <form id="form1" name="form1" method="post" action="">
      <a type="button" href="<?php echo URL_PATH; ?>purchase/shoppingcart" class="sidecheckout">Check out</a>
      </form>
      </div>
      </div>
<div id="hidden_test">
<img src="<?php echo PUBLIC_PATH; ?>images/background-testhalf.png" />
</div>
<div id="testxiaobing"><img src="<?php echo PUBLIC_PATH; ?>images/background-teatxiaobing.png" /></div>
<div id="teatesttext"> <a href="<?php echo URL_PATH; ?>index/test" >Tea Test</a></div>
</div>