<link rel="stylesheet" href="<?php echo APPLICATION_PUBLIC_PATH; ?>/css/slider.css" />
<script src="<?php echo APPLICATION_PUBLIC_PATH;?>/js/jquery.flexslider.min.js"
type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function($) {
        $("#slider").flexslider({
            controlNav : false,
            directionNav : true,
            animationLoop : true,
            animation : "fade",
            useCSS : false,
            video : true,
            smoothHeight : true,
            slideshow : true,
            slideshowSpeed : 10000,
            pauseOnAction : true,
            animationSpeed : 600
        });
    });

</script>
<div id="slider" style="height: 550px;">
    <ul class="slides">
    <?php 
    $slider = $this->slider;
    $sliderTable = $this->sliderTable;
    foreach ($slider as $item) {
    ?>
        <li>
            <a
            href="<?php echo $item[$sliderTable->detailUrl] == null ? '#' : $item[$sliderTable->detailUrl]; ?>"
            title="<?php echo $item[$sliderTable->title]; ?>"><img
            src="<?php echo $item[$sliderTable->imageUrl]; ?>"
            alt="<?php echo $item[$sliderTable->title]; ?>" class="Thumbnail thumbnail featured "
            width="980" height="550" /></a>
            <div class="slide_content">
                <h5><a
                href="<?php echo $item[$sliderTable->detailUrl] == null ? '#' : $item[$sliderTable->detailUrl]; ?>"
                title="<?php echo $item[$sliderTable->title]; ?>"><?php echo $item[$sliderTable->title]; ?></a> </h2>
                <p>
                    <?php echo $item[$sliderTable->description]; ?>
                </p>
            </div>
        </li>
    <?php 
    }
    ?>
    </ul>
    <!-- /.slides -->
    <ul class="flex-direction-nav">
        <li>
            <a class="flex-prev" href="#">上一张</a>
        </li>
        <li>
            <a class="flex-next" href="#">下一张</a>
        </li>
    </ul>
</div>