<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type='text/javascript'
	src='<?php
echo APPLICATION_PUBLIC_PATH;
?>/js/jquery-1.8.3.min.js'></script>
<script type='text/javascript'
	src='<?php
echo APPLICATION_PUBLIC_PATH;
?>/js/jquery.placeholder.js'></script>
<script
	src="http://l.tbcdn.cn/apps/top/x/sdk.js?appkey=<?php
echo $this->getTaobaoAppkey();
?>"></script>
<title>获取返利链接</title>
</head>
<body>
<?php
$this->setTaobaoCookies();
?>
<input type="text" id="search" style="width: 400px"
	placeholder="请输入商品链接" />
<input type="button" id="btn" value="获取返利链接" />
<p><a id="url" target="_blank"></a></p>
<p id="fanli"></p>
<p id="image"></p>
<script type="text/javascript">
$(function(){
	$('#btn').click(function(){
		var url = $('#search').val();
		var contact = $('#contact').val();
		$.ajax({
			url : '<?php
echo APPLICATION_ACTION_PATH;
?>/goods/get-product-id', 
			data : {url:url}, 
			success : function(data){
				if (data.errorcode == -1) {
					noBack(url, data.result);
				} else if (data.errorcode == -2) {
					alert('请输入合法的淘宝商品链接!');
				} else {
					TOP.api('rest', 'get', {
						method : 'taobao.taobaoke.widget.items.convert',
						num_iids : data.result,
						fields : 'title,click_url,pic_url,price,commission_rate'
					}, function(resp) {
						if(resp.error_response) {
							alert('taobao.taobaoke.widget.items.convert接口获取商品信息品失败!' + resp.error_response.msg);
							return false;
						}
						if (resp.total_results > 0) {
							var respItem = resp.taobaoke_items.taobaoke_item;
							$('#url').attr('href', respItem[0].click_url);
							$('#url').html(respItem[0].title);
							$('#image').html('<a href="' + respItem[0].click_url + '" target="_blank"><img src="' + respItem[0].pic_url + '" height="230px" width="230px"/></a>');
						} else {
							noBack(url, data.result);
						}
					});
				}
			}
		});
	});
});

function noBack(url, result)
{
	$('#url').attr('href', url);
	$('#url').html(result.title);
	$('#fanli').html('<span style="color:red;">该商品暂时没有返利!</span>');
	$('#image').html('<a href="' + url + '" target="_blank"><img src="' + result.picurl + '" height="230px" width="230px"/></a>');
}
</script>
</body>
</html>