<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="content_top">
		<div class="home_top_box mb20 r5">
            <div class="home_top_bg rt5"  style="background-image:url(http://s6.mogujie.cn/b7/pic/120831/93nyl_kqyvq4lcl5bfqv2ugfjeg5sckzsew_960x170.jpg_960x400.jpg);">
				<div class="home_top_all"><span class="h_t_bg"></span>
					<div class="top_avatar"><img alt="<?php echo $this->userinfo['username']?>" src="<?php echo APPLICATION_PUBLIC_PATH . '/avatar/' . $this->userinfo['avatar']?>" class="r5 u_i">
						<ul class="record">
							<li class="fans">
							<a title="关注" href="/u/122nqg/follow"><span class="ft18">14</span><span>关注</span></a>
							</li>                                        
							<li class="popular"><a title="粉丝" href="/u/122nqg/fans"><span class="ft18">12</span><span>粉丝</span></a></li>
                            <li class="liked">
								<div>
									<span class="ft18">0</span>
									<span class="t" >被喜欢</span>
								</div>
							</li> 				           
											
						</ul>
					</div> 
					<div class="home_top_user">
						<div class="name_fav">
                            <h1 class="fl"><a href="<?php echo APPLICATION_ACTION_PATH; ?>/user/info" title="<?php echo $this->userinfo['username']?>" ><?php echo $this->userinfo['username']?></a></h1>
                            <div type="all" uid="122nqg" class="followdiv fl"></div>
                        </div>
                        <p class="home_top_p">
                        <a href="/u/122nqg/settingdetail" target="_blank" >查看更多<span>&gt;&gt;</span></a>
                        </p>
                        <p class="home_top_x"><span>职业/学生</span>        
							</p>
                        <p class="home_top_x user_label"></p>
                    </div>
                        <a class="ht_more_info" href="<?php echo APPLICATION_ACTION_PATH; ?>/user/info">个人设置</a>
                </div>
            </div>
            <div class="home_top_nav rb5">
                <ul class="home_nav">
                    <li class="c"><a class="usertype" href="###" title="喜欢" type="like" >喜欢</a></li>
					<li><a class="usertype" href="###" title="分享" type="share" >分享</a></li>
                </ul>
            </div>
        </div>                
	</div>
    <?php
    echo $this->render('common/block.phtml');
    ?>
    <script type="text/javascript">
    var userid = <?php echo $this->userinfo['id']; ?>;
    var usertype = 'like';
    $('#useridValue').val(userid);
    $('#usertypeValue').val(usertype);
    </script>
</div>
<?php
echo $this->render('common/footer.phtml');
?>
