<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="content_top">
		<div class="home_top_box mb20 r5">
            <div class="home_top_bg rt5"  style="background-image:url(http://s6.mogujie.cn/b7/pic/120831/93nyl_kqyvq4lcl5bfqv2ugfjeg5sckzsew_960x170.jpg_960x400.jpg);">
				<div class="home_top_all"><span class="h_t_bg"></span>
					<div class="top_avatar"><img alt="点点0123" src="http://s5.mogujie.cn/b1/avatar/111029/11bug_kqyweyk7krbegzdwgfjeg5sckzsew_720x420.jpg_185x185.jpg" class="r5 u_i">
						<ul class="record">
							<li class="fans">
							<a title="关注" href="/u/122nqg/follow"><span class="ft18">14</span><span>关注</span></a>
							</li>                                        
							<li class="popular"><a title="粉丝" href="/u/122nqg/fans"><span class="ft18">12</span><span>粉丝</span></a></li>
                            <li class="liked">
								<div>
									<span class="ft18">0</span>
									<span class="t" >被喜欢</span>
								</div>
							</li> 				           
											
						</ul>
					</div> 
					<div class="home_top_user">
						<div class="name_fav">
                            <h1 class="fl"><a href="<?php echo APPLICATION_ACTION_PATH; ?>/user/info" title="点点0123" >点点0123</a></h1>
                            <div type="all" uid="122nqg" class="followdiv fl"></div>
                        </div>
                        <p class="home_top_p">
                        <a href="/u/122nqg/settingdetail" target="_blank" >查看更多<span>&gt;&gt;</span></a>
                        </p>
                        <p class="home_top_x"><span>职业/学生</span>        
							</p>
                        <p class="home_top_x user_label"></p>
                    </div>
                        <a class="ht_more_info" href="personal.html">个人设置</a>
                </div>
            </div>
            <div class="home_top_nav rb5">
                <ul class="home_nav">
                    <li class="c"><a href="/cover/u/122nqg" title="封面" >喜欢</a></li>
					<li><a href="/u/122nqg/fav" title="喜欢" >分享</a></li>
                </ul>
            </div>
        </div>                
	</div>

</div>
<?php
echo $this->render('common/footer.phtml');
?>
