<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="body" class="fm960">
			<div class="piece1">
				<div class="piece1_hd"></div>
				<div class="piece1_bd clearfix">
					<div id="content" style="width:960px;">
<?php
echo $this->render('common/navi.phtml');
?>
						<div id="setting_box" class="fl">
							<div id="setting_form" class="setting_basic">
								<form action="" method="post">
								<div class="settings_title">
								<span>基本资料</span>
								</div>
								<dl>
								<dd>昵称：</dd>
								<dt class="unick">
									<input class="r3" type="text" name="unick" value="点点0123" /><div class="iner" style="color:#666;"><span>*</span>昵称只能修改一次哦^_^</div>
								</dt>
				
								<dd>性别：</dd>
								<dt class="sex" style="line-height: 30px;">
									<input checked name="sex" value="2" type="radio" id="" style="margin:0">女
									<input  name="sex" type="radio" value="1" id="">男
								</dt>
								<dd>邮箱：</dd>
								<dt style="padding-top:5px;">
									3490*****@qq.com<span style='color:#FF5697; padding-left:5px;'>(未认证)</span><a href='/settings/bindemail/' style='color:blue;  padding-left:5px'>去认证 >></a>		</dt>
								<dd>个人博客：</dd>
								<dt class="weibo"><input class="r3" name="weibo" type="text" value="" /></dt>
		
								<dd>所在地：</dd>
								<dt class="location">
								<select id="province" name="province"></select>&nbsp;&nbsp;
								<select id="city" name="city"></select>
								</dt>
								<script type="text/javascript">
								initPlace('杭州','浙江');
								</script>
								<dd>生日：</dd>
								<dt class="birthday">
								<select name="born[]" >
								<option></option>
									<option  value="2009">2009</option>
									<option  value="2008">2008</option>
									<option  value="2007">2007</option>
									<option  value="2006">2006</option>
									<option  value="2005">2005</option>
									<option  value="2004">2004</option>
									<option  value="2003">2003</option>
									<option  value="2002">2002</option>
									<option  value="2001">2001</option>
									<option  value="2000">2000</option>
									<option  value="1999">1999</option>
									<option  value="1998">1998</option>
									<option  value="1997">1997</option>
									<option  value="1996">1996</option>
									<option  value="1995">1995</option>
									<option  value="1994">1994</option>
									<option  value="1993">1993</option>
									<option  value="1992">1992</option>
									<option  value="1991">1991</option>
									<option  value="1990">1990</option>
									<option  value="1989">1989</option>
									<option  value="1988">1988</option>
									<option  value="1987">1987</option>
									<option  value="1986">1986</option>
									<option  value="1985">1985</option>
									<option  value="1984">1984</option>
									<option  value="1983">1983</option>
									<option  value="1982">1982</option>
									<option  value="1981">1981</option>
									<option  value="1980">1980</option>
									<option  value="1979">1979</option>
									<option  value="1978">1978</option>
									<option  value="1977">1977</option>
									<option  value="1976">1976</option>
									<option  value="1975">1975</option>
									<option  value="1974">1974</option>
									<option  value="1973">1973</option>
									</select>&nbsp;年&nbsp;
									<select name="born[]" id="month">
								<option></option>
									<option  value="1">1</option>
									<option  value="2">2</option>
									<option  value="3">3</option>
									<option  value="4">4</option>
									<option  value="5">5</option>
									<option  value="6">6</option>
									<option  value="7">7</option>
									<option  value="8">8</option>
									<option  value="9">9</option>
									<option  value="10">10</option>
									<option  value="11">11</option>
									<option  value="12">12</option>
								</select>&nbsp;月&nbsp;
								<select name="born[]" id="day">
								<option></option>
									<option  value="1">1</option>
									<option  value="2">2</option>
									<option  value="3">3</option>
									<option  value="4">4</option>
									<option  value="5">5</option>
									<option  value="6">6</option>
									<option  value="7">7</option>
									<option  value="8">8</option>
									<option  value="9">9</option>
									<option  value="10">10</option>
									<option  value="11">11</option>
									<option  value="12">12</option>
									<option  value="13">13</option>
									<option  value="14">14</option>
									<option  value="15">15</option>
									<option  value="16">16</option>
									<option  value="17">17</option>
									<option  value="18">18</option>
									<option  value="19">19</option>
									<option  value="20">20</option>
									<option  value="21">21</option>
									<option  value="22">22</option>
									<option  value="23">23</option>
									<option  value="24">24</option>
									<option  value="25">25</option>
									<option  value="26">26</option>
									<option  value="27">27</option>
									<option  value="28">28</option>
									<option  value="29">29</option>
									<option  value="30">30</option>
									<option  value="31">31</option>
								</select>&nbsp;日
								</dt>
		
							<dd>星座：</dd>
							<dt class="constellation">
								<select id="constellation" name="constellation">
									<option id="xingzuo_name"></option>
									<option>水瓶座</option>
									<option>双鱼座</option>
									<option>白羊座</option>
									<option>金牛座</option>
									<option>双子座</option>
									<option>巨蟹座</option>
									<option>狮子座</option>
									<option>处女座</option>
									<option>天秤座</option>
									<option>天蝎座</option>
									<option>射手座</option>
									<option>摩羯座</option>
								</select>
							</dt>
							<dd>职业：</dd>
							<dt class="profession">
								<select id="profession" name="profession">
									<option>学生</option>
									<option>白领</option>
									<option>学生</option>
									<option>时尚店主</option>
									<option>传媒</option>
									<option>艺术</option>
									<option>其他</option>
								</select>
							</dt>
						</dl>
						<div class="settings_title mt30">
							<span>其他信息</span>
						</div>
						<dl>
                
							<dd>个人标签：</dd>
							<dt style="margin-bottom:5px;position:relative;" >
							<input autocomplete="off" style=" color:#999" id="user_style" name="personstyle" class="gray_text pstyle r3" type="text" value="多个标签之间请用逗号隔开">
							<div class="fashion_list">
								<span class="tag">
								<a style="color:#ff3998;font-size:14px;">上网</a>
								<a style="color:#ff7878;font-size:12px;">摄影</a>
								<a style="color:#76ad00;font-size:16px;">宅女</a>
								<a style="color:#84a9f4;font-size:16px;">美剧</a>
								<a style="color:#ff683f;font-size:14px;">大学</a>
								<a style="color:#ff3998;font-size:16px;">传媒</a>
								<a style="color:#327aff;font-size:16px;">80后</a>
								<a style="color:#327aff;font-size:12px;">小说</a>
								<a style="color:#327aff;font-size:16px;">娱乐</a>
								<a style="color:#ff3998;font-size:14px;">八卦</a>
								<a style="color:#84a9f4;font-size:16px;">休闲</a>
								<a style="color:#ff7878;font-size:12px;">小清新</a>
								<a style="color:#84a9f4;font-size:16px;">居家</a>
								<a style="color:#76ad00;font-size:12px;">约会</a>
								<a style="color:#ff3998;font-size:16px;">美食</a>
								<a style="color:#ff7878;font-size:12px;">卡通</a>
								<a style="color:#76ad00;font-size:16px;">动漫</a>
								<a style="color:#ff7878;font-size:16px;">DIY</a>
								<a style="color:#327aff;font-size:14px;">中性</a>
								<a style="color:#76ad00;font-size:12px;">配饰控</a>
								</span>
								<a class="close" href="javascript:;"></a>
							</div>
							</dt>
	
	
							<dd>自我介绍：</dd>
							<dt><textarea name="introduce" id="" rows="10" class="r3" >随便写点什么，让大家了解你吧。</textarea></dt>

							<dd>&nbsp;&nbsp;</dd>
							<dt><input class="green_button r3" type="button" value="确认修改"></dt>
						</dl>
					</form>
					</div>
				</div>

               </div>
            </div>
           <div class="piece1_ft"></div>
	</div>
</div>

</div>
<?php
echo $this->render('common/footer.phtml');
?>