<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="body" class="fm960">
			<div class="piece1">
				<div class="piece1_hd"></div>
				<div class="piece1_bd clearfix">
					<div id="content" style="width:960px;">
<?php
echo $this->render('common/navi.phtml');
?>
<script type='text/javascript' src='<?php echo APPLICATION_PUBLIC_PATH; ?>/js/info.js'></script>
<?php 
$info = $this->userinfo;
?>
						<div id="setting_box" class="fl">
							<div id="setting_form" class="setting_basic">
								<form action="" method="post">
								<div class="settings_title">
								<span>基本资料</span>
								</div>
								<dl>
								<dd>昵称：</dd>
								<dt class="unick">
									<input class="r3" type="text" id="usrname" value="<?php echo $info['username'];?>" /><div class="iner" style="color:#666;"></div>
								</dt>
								<dd>性别：</dd>
								<dt class="sex" style="line-height: 30px;">
								<?php 
								if ($info['gender'] == 0) {
                                ?>
								<input checked name="gender" value="0" type="radio" id="female" style="margin:0;width:25px;">女
                                <input name="gender" type="radio" value="1" id="male" style="margin:0;width:25px;">男
								<?php
								} else {
								?>
								<input name="gender" value="0" type="radio" id="" style="margin:0;width:25px;">女
                                <input checked name="gender" type="radio" value="1" id="" style="margin:0;width:25px;">男
							    <?php 
							    }
							    ?>
								</dt>
								<dd>邮箱：</dd>
								<dt>
									<input class="r3" type="text" id="email" value="<?php echo $info['email'];?>" /><div class="iner" style="color:#666;"></div>
								<dd>个人博客：</dd>
								<dt class="weibo"><input class="r3" id="blog" type="text" value="<?php echo $info['blog'];?>" /></dt>
		
								<dd>所在地：</dd>
								<dt class="location">
								<select id="province-select" class="selection" name="province">
									<option value="0">请选择</option>
									<?php
                                    $resultProvince = $this->province;
                                    $sele = $info['province'];
                                    foreach ($resultProvince as $province) {
                                        if ($sele == $province['code']) {
                                            echo '<option value="' . $province['code'] . '" selected>' . $province['name'] . '</option>';
                                        } else {
                                            echo '<option value="' . $province['code'] . '" >' . $province['name'] . '</option>';
                                        }
                                    }
									?>
								</select>
								<select id="city-select" class="selection" name="city">
									<option value="0"></option>
									<?php
                                    echo $this->city;
									?>
								</select>
								<select id="district-select" class="selection" name="district">
									<option value="0"></option>
									<?php
                                    echo $this->district;
									?>
								</select>
								</dt>
								<dd>生日：</dd>
								<dt class="birthday">
								<select id="year-select" class="selection"
								name="year">
									<option value="0"></option>
									<?php
									if (empty($info['birthday'])) {
									    $year = null;
									} else {
									    $year = date('Y', strtotime($info['birthday']));
									}
                                    for ($i = 2012; $i >= 1900; $i--) {
                                        if ($year == $i) {
                                            echo '<option value="' . $i . '" selected>' . $i . '</option>';
                                        } else {
                                            echo '<option value="' . $i . '" >' . $i . '</option>';
                                        }
                                    }
									?>
								</select>&nbsp;年&nbsp;
									<select id="month-select" class="selection" name="month">
									<option value="0"></option>
									<?php
									if (empty($info['birthday'])) {
									    $month = null;
									} else {
									    $month = date('m', strtotime($info['birthday']));
									}
                                    for ($i = 1; $i <= 12; $i++) {
                                        if ($month == $i) {
                                            if ($i < 10) {
                                                echo '<option value="0' . $i . '" selected>0' . $i . '</option>';
                                            } else {
                                                echo '<option value="' . $i . '" selected>' . $i . '</option>';
                                            }
                                        } else {
                                            if ($i < 10) {
                                                echo '<option value="0' . $i . '" >0' . $i . '</option>';
                                            } else {
                                                echo '<option value="' . $i . '" >' . $i . '</option>';
                                            }
                                        }
                                    }
									?>
								</select>&nbsp;月&nbsp;
								<select id="day-select" class="selection" name="day">
									<option value="0"></option>
									<?php
									if (empty($info['birthday'])) {
									    $day = null;
									} else {
                                        $day = date('d', strtotime($info['birthday']));
									}
                                    if ($year % 100 == 0) {
                                        if ($year % 400 == 0) {
                                            $smooth = true;
                                        } else {
                                            $smooth = false;
                                        }
                                    } elseif ($year % 4 == 0) {
                                        $smooth = true;
                                    } else {
                                        $smooth = false;
                                    }
                                    if ($month == 1 || $month == 3 || $month == 5 || $month == 7 || $month == 8 || $month == 10 || $month == 12) {
                                        for ($i = 1; $i <= 31; $i++) {
                                            if ($day == $i) {
                                                if ($i < 10) {
                                                    echo '<option value="0' . $i . '" selected>0' . $i . '</option>';
                                                } else {
                                                    echo '<option value="' . $i . '" selected>' . $i . '</option>';
                                                }
                                            } else {
                                                if ($i < 10) {
                                                    echo '<option value="0' . $i . '" >0' . $i . '</option>';
                                                } else {
                                                    echo '<option value="' . $i . '" >' . $i . '</option>';
                                                }
                                            }
                                        }
                                    } elseif ($month == 4 || $month == 6 || $month == 9 || $month == 11) {
                                        for ($i = 1; $i <= 30; $i++) {
                                            if ($day == $i) {
                                                if ($i < 10) {
                                                    echo '<option value="0' . $i . '" selected>0' . $i . '</option>';
                                                } else {
                                                    echo '<option value="' . $i . '" selected>' . $i . '</option>';
                                                }
                                            } else {
                                                if ($i < 10) {
                                                    echo '<option value="0' . $i . '" >0' . $i . '</option>';
                                                } else {
                                                    echo '<option value="' . $i . '" >' . $i . '</option>';
                                                }
                                            }
                                        }
                                    } else {
                                        if ($smooth) {
                                            for ($i = 1; $i <= 29; $i++) {
                                                if ($day == $i) {
                                                    if ($i < 10) {
                                                        echo '<option value="0' . $i . '" selected>0' . $i . '</option>';
                                                    } else {
                                                        echo '<option value="' . $i . '" selected>' . $i . '</option>';
                                                    }
                                                } else {
                                                    if ($i < 10) {
                                                        echo '<option value="0' . $i . '" >0' . $i . '</option>';
                                                    } else {
                                                        echo '<option value="' . $i . '" >' . $i . '</option>';
                                                    }
                                                }
                                            }
                                        } else {
                                            for ($i = 1; $i <= 28; $i++) {
                                                if ($day == $i) {
                                                    if ($i < 10) {
                                                        echo '<option value="0' . $i . '" selected>0' . $i . '</option>';
                                                    } else {
                                                        echo '<option value="' . $i . '" selected>' . $i . '</option>';
                                                    }
                                                } else {
                                                    if ($i < 10) {
                                                        echo '<option value="0' . $i . '" >0' . $i . '</option>';
                                                    } else {
                                                        echo '<option value="' . $i . '" >' . $i . '</option>';
                                                    }
                                                }
                                            }
                                        }
                                    }
									?>
								</select>&nbsp;日
								</dt>
							<dd>职业：</dd>
							<dt class="profession">
								<select id="occupation" name="occupation">
								<option value="0"></option>
								<?php 
								foreach ($this->occupation as $item) {
                                    if ($item['id'] == $info['occupation']) {
                                ?>
									<option selected value="<?php echo $item['id']?>"><?php echo $item['name']; ?></option>
								<?php 
                                    } else {
								?>
									<option value="<?php echo $item['id']?>"><?php echo $item['name']; ?></option>
								<?php 
								    }
								}
								?>
								</select>
							</dt>
						</dl>
						<dd>自我介绍：</dd>
						<dt><textarea name="introduce" id="" rows="10" class="r3" ><?php echo $info['introduction']; ?></textarea></dt>
							<dd>&nbsp;&nbsp;</dd>
							<dt><input id="submitUpdate" class="green_button r3" type="button" value="确认修改"></dt>
						</dl>
					</form>
					</div>
				</div>

               </div>
            </div>
           <div class="piece1_ft"></div>
	</div>
</div>
</div>
<?php
echo $this->render('common/footer.phtml');
?>