<?php
echo $this->render('common/header.phtml');
?>
<?php

echo $this->render('common/menu.phtml');
?>
<div id="container">
	<!--content-->
	<div id="body" class="fm960">
		<div class="piece1">
			<div class="piece1_hd"></div>
			<div class="piece1_bd clearfix">
				<div id="content" style="width: 960px;">
<?php
echo $this->render('common/navi.phtml');
?>
				<div id="setting_box" class="fl">

						<div id="setting_form" class="setting_password">
							<!-- 修改部分开始 -->
							<form id="resetpassword" action="/usersecurity/ajaxmodifypwd"
								method="post">
								<div class="settings_title">
									<span>修改密码</span>
								</div>
								<dl>
									<dd>现在的密码：</dd>
									<dt class="clearfix">
										<input id="oldPwd" class="gray_text r5" type="password" value="">
										<span id="oldPwdTip" class="tip" style=""></span>
									</dt>
									<dd>新的密码：</dd>
									<dt class="clearfix">
										<input id="newPwd1" class="gray_text r5" type="password">
										<span id="newPwd1Tip" class="tip" style=""></span>
									</dt>
									<dd>确认新的密码：</dd>
									<dt class="clearfix">
										<input id="newPwd2" class="gray_text r5" type="password" value="">
										<span id="newPwd2Tip" class="tip" style=""></span>
									</dt>
									<dd>&nbsp;</dd>
									<dt class="clearfix subbox">
										<input id="changePassword" class="submit r3" type="button"
											value="确认修改">
									</dt>
								</dl>
							</form>
							<!-- 修改部分结束 -->
						</div>
					</div>
				</div>
			</div>

			<div class="piece1_ft"></div>
		</div>
	</div>
</div>
<<script type="text/javascript" src="<?php echo APPLICATION_PUBLIC_PATH; ?>/js/change-password.js">
</script>
<?php
echo $this->render('common/footer.phtml');
?>