<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="body" class="fm960">
			<div class="piece1">
				<div class="piece1_hd"></div>
				<div class="piece1_bd clearfix">
					<div id="content" style="width:960px;">
<?php
echo $this->render('common/navi.phtml');
?>
				<div id="setting_box" class="fl">

				 <div id="setting_form" class="setting_password">
				 	<!-- 修改部分开始 -->
				      <form id="resetpassword" action="/usersecurity/ajaxmodifypwd" method="post">
			      		  <div class="settings_title">
					    	<span>修改密码</span>
					      </div>
			              <dl>
		                      <dd>现在的密码：</dd>
		                      <dt class="clearfix"><input name="oldPwd" class="gray_text r5" type="password" value=""></dt>
		                      <dd>新的密码：</dd>
		                      <dt class="clearfix">
                                <input id="password" name="newPwd1" class="gray_text r5" type="password" data-succssed="if(formaajax_catchdata.result.level){var d = parseInt(formaajax_catchdata.result.level) - 1; $('.level').show();$('.level span').removeClass('current');$('.level span').eq(d).addClass('current');}" data-ajax='{ "url" : "/usersecurity/ajaxcheckpwdlevel" , "type" : "POST" , "dataname" : "pwd" , "max" : 18 , "min" : 6 }' data-errormsg="密码长度应为6~16个字符">

                                <span class="tip" style="">密码长度应为6~16个字符</span>
		                      </dt>
		                      <dd>确认新的密码：</dd>
		                      <dt class="clearfix"><input data-type="repassed" data-passed="password" name="newPwd2" class="gray_text r5" type="password" value=""></dt>
		                      <dd>验证码：</dd>
		                      <dt class="clearfix">
		                      	<input type="text" maxlength="4" class="gray_text checekcode r3" name="validCode">
		                      	<img src="/captcha/51827cb42ffc8" id="img_checkcode" alt="验证码" />
		                      	<a href="javascript:void(0);" id="checkcode_change">换一张</a>
		                      </dt>
		                      <dd>&nbsp;</dd>
		                      <dt class="clearfix subbox"><input class="submit r3" type="button" value="确认修改"> <span class="reset">取消</span></dt>
			              </dl>
				      </form>
				    <!-- 修改部分结束 -->
				 </div>
				</div>
                </div>
            </div>

           <div class="piece1_ft"></div>
	</div>
</div>

</div>
<?php
echo $this->render('common/footer.phtml');
?>