<?php
echo $this->render('common/header.phtml');
?>
<?php

echo $this->render('common/menu.phtml');
?>
<div id="registration">
	<div id="register">
		<h1>Gift新会员注册</h1>
		<div class="blank15"></div>
		<span>加入gift，发现最美好的礼物，分享选购礼品乐趣。</span>
		<div id="register_center">
			<div id="register_form">
				<form action="/user/registration" method="post" id="registerForm">
					<div class="ipt_ulike">
						<span>昵称：</span> <input style="*margin-left: -1px;" maxlength="36"
							type="text" name="username" id="reg_user_name" class="text"
							value="<?php echo $this->username; ?>" istip="0" rel=".err_ulike" check="0">
					</div>
					<div class="ipt_password">
						<span>密码：</span> <input style="*margin-left: -1px;" maxlength="36"
							type="password" name="pwd1" id="reg_password" class="text"
							istip="0" rel=".err_password" check="0">
					</div>
					<div class="ipt_respassword">
						<span>确认密码：</span> <input type="password" maxlength="36"
							name="pwd2" id="reg_cpassword" class="text" istip="0"
							rel=".err_rstpassword" check="0">
					</div>
					<div class="ipt_check">
						<span>验证码：</span> <input class="check" type="text" maxlength="10"
							name="code"> <img id="img_checkcode" alt="验证码"
							src="<?php echo '/' . $this->captchaDir . $this->captchaId?>.png">
						<a id="changeCaptcha" href="###">换一张</a>
					</div>
					<div class="ipt_sub">
						<input type="submit" class="sub" id="reg_submit" value="立即注册">
						<div class="lg_reg_loading">
							<span style="font-size: 13px;">注册中，请稍候...</span>
						</div>
					</div>
					<input name="rhash" id="regRHash" value="521ac1ad" type="hidden"> <input
						name="refer" value="/settings/bind" type="hidden"> <input
						name="action" value="ajax_register" type="hidden">
				</form>
			</div>
			<div id="register_error">
				<div class="err_ulike"><?php
                if (isset($this->usernameHint)) {
                    echo $this->usernameHint;
                } else {
                ?>支持中文，由6~20个字符组成，中文算两个字符。<?php } ?></div>
				<div class="err_password"><?php
                if (isset($this->pwd1Hint)) {
                    echo $this->pwd1Hint;
                } else {
                ?>6-20个字母、数字或者符号<?php } ?></div>
				<div class="err_rstpassword"><?php
                if (isset($this->pwd2Hint)) {
                    echo $this->pwd2Hint;
                } else {
                ?>这里要重复输入一下你的密码<?php } ?></div>
				<div class="err_captcha"><?php
                if (isset($this->codeHint)) {
                    echo $this->codeHint;
                } else {
                ?>这里要输入验证码<?php } ?></div>
			</div>
		</div>
	</div>
<?php
echo $this->render('common/footer.phtml');
?>