<?php
echo $this->render('common/header.phtml');
?>
<?php

echo $this->render('common/menu.phtml');
?>
<div id="container">
	<!--content-->
	<div id="talk_content">
		<div id="talk_title">
			<div class="gr_info r5">
				<h2>Gift 讨论吧</h2>
				无主题的主题吧，欢迎扎堆唠嗑。
			</div>
		</div>
	</div>
	<div class="core">
		<div class="core_title_wrap" style="">
			<div class="core_title core_title_theme2">
				<a class="core_title_go_top" href="###">
					<h1 class="core_title_txt"
						title="<?php echo $this->article->title;?>"><?php echo $this->article->title; ?></h1>
				</a>
			</div>
		</div>
		<input type="hidden" value="<?php echo $this->article->id; ?>"
			id="articleId" />
		<div class="p_postlist">
		<?php
$userinfo = $this->getUserInfo($this->article->author);
?>
			<div class="l_post noborder">
				<a class="l_post_anchor"></a>
				<div class="d_author">
					<div class="louzhubiaoshi_wrap">
						<div class="louzhubiaoshi">
							<a href="/p/2336142763?pid=32914033419&amp;see_lz=1#32914033419"></a>
						</div>
					</div>
					<ul class="p_author post_icon">
						<li>
							<div class="icon_relative" style="padding: 4px; margin-top: 2px;">
								<a class="p_author_face"
									href="/i/315242756?st_mod=pb&amp;fr=tb0_forum&amp;st_type=uface"
									target="_blank"><img class="avatar"
									src="<?php echo APPLICATION_PUBLIC_PATH . $userinfo['avatar'] ?>"
									data-passive="loaded" style="width: 80px; height: 80px"></a>
							</div>
						</li>
						<li class="d_name"><a class="p_author_name" href="###"
							target="_blank"><?php echo $userinfo['username'] ?></a></li>
					</ul>
				</div>

				<div class="d_post_content_main ">
					<div class="p_content"><?php echo $this->article->content; ?> </div>

					<div class="core_reply">
						<a class="l_post_anchor"></a>
						<div class="core_reply_tail">
							<ul class="p_reply">
								<li><a href="#new_topic" class="p_reply_first"
									style="cursor: pointer">回复</a></li>
							</ul>

							<ul class="p_tail">
								<li><span class="">1楼</span></li>
								<li><span><?php echo $this->article->ctime; ?></span></li>
							</ul>
						</div>
						<div class="core_reply_wrapper " style="display: none">
							<div class="core_reply_border_top"></div>
							<div class="core_reply_content">
								<ul style="display: none">
									<li class="lzl_li_pager lzl_li_pager_s"
										data-field="{&quot;total_num&quot;:&quot;&quot;,&quot;total_page&quot;:&quot;&quot;}">
										<p>
											<a href="##">我也说一句</a>
										</p>
										<p>&nbsp;</p>

									</li>
								</ul>
								<div class="lzl_editor_container lzl_editor_container_s"
									style="display: none;"></div>
								<input type="text" style="display: none;">
							</div>
							<div class="core_reply_border_bottom"></div>
						</div>
					</div>

				</div>
				<div class="clear"></div>
			</div>
<?php
foreach ($this->replys as $key => $reply) :
    $floor = $reply['floor'];
    $subFloors = $reply['subFloors'];
    $userinfo = $this->getUserInfo($floor['author']);
    ?>
		<div class="l_post ">
				<a class="l_post_anchor"></a>
				<div class="d_author">
				<?php
    if ($this->article->author == $userinfo['id']) {
        ;
        ?>
				    <div class="louzhubiaoshi_wrap">
						<div class="louzhubiaoshi">
							<a href="/p/2336142763?pid=32914033419&amp;see_lz=1#32914033419"></a>
						</div>
					</div>
				<?php
    }
    ?>
					<ul class="p_author post_icon">
						<li>
							<div class="icon_relative" style="padding: 4px; margin-top: 2px;">
								<a class="p_author_face"
									href="/i/315242756?st_mod=pb&amp;fr=tb0_forum&amp;st_type=uface"
									target="_blank"><img class="avatar"
									src="<?php echo APPLICATION_PUBLIC_PATH . $userinfo['avatar'] ?>"
									data-passive="loaded" style="width: 80px; height: 80px"></a>
							</div>
						</li>
						<li class="d_name"><a class="p_author_name sign_highlight"><?php echo $userinfo['username'] ?></a></li>
					</ul>
				</div>

				<div class="d_post_content_main ">
					<div class="p_content"><?php echo $floor['content'];?> </div>
					<div class="core_reply">
<?php if (!empty($subFloors)) : ?>
						<a class="l_post_anchor"></a>
						<div class="core_reply_tail">
							<div class="p_reply" style="cursor: pointer">
								<a href="###" class="lzl_link_unfold"
									style="display:; cursor: pointer">收起回复</a>
							</div>

							<ul class="p_tail">
								<li><span class=""><?php echo $key + 2; ?>楼</span></li>
								<li><span><?php echo $floor['ctime']?></span></li>
							</ul>
						</div>

						<div class="core_reply_wrapper " style="display:">
							<div class="core_reply_border_top"></div>
							<div class="core_reply_content">
								<ul style="display:">
<?php
        
        foreach ($subFloors as $subFloor) :
            $authorInfo = $this->getUserInfo($subFloor['author']);
            ?>
                <li class="lzl_single_post first_no_border"><a
										class="l_post_anchor"></a> <a class="lzl_p_p"
										href="/i/103280686?st_mod=pb&amp;fr=tb0_forum&amp;st_type=uface"
										target="_blank"> <img class="forscrollasync"
											src="<?php echo APPLICATION_PUBLIC_PATH . $authorInfo['avatar']; ?>"
											style="width: 32px; height: 32px">
									</a>
										<div class="lzl_cnt">
											<a class="at" href="###"><?php
            echo $authorInfo['username'];
            ?></a>
            <?php 
            if ($subFloor['reply_to'] != $floor['id']) {
            ?>
                                回复 <a class="at" href="###"><?php
            $replyAuthorInfo = $this->getUserInfo($subFloor['reply_to_author']);
            echo $replyAuthorInfo['username'];
            ?></a>
            <?php    
            }
            ?>
                                ：<span class="lzl_content_main"><?php echo $subFloor['content']; ?> </span>
											<div class="lzl_content_reply">
												<span class="lzl_op_list" style="display: none;"></span> <span
													class="lzl_time"><?php echo $subFloor['ctime']; ?></span> <a
													href="###" class="lzl_s_r">回复</a> <input type="hidden"
													class="replyToAuthor"
													value="<?php echo $subFloor['author'];?>" /> <input
													type="hidden" class="replyTo"
													value="<?php echo $subFloor['id'];?>" /> <input
													type="hidden" class="replyToUsername"
													value="<?php 
													$replyToUserinfo = $this->getUserInfo($subFloor['author']);
													echo $replyToUserinfo['username'];
													?>" />
											</div>
										</div></li>
<?php endforeach;?>
										<li class="lzl_li_pager lzl_li_pager_s">
										<p class="j_lzl_p">
											<a href="###">我也说一句</a>
										</p> <input type="hidden" class="replyToAuthor"
										value="<?php echo $floor['author'];?>" /> <input type="hidden"
										class="replyTo" value="<?php echo $floor['id'];?>" />
										<p>&nbsp;</p>

									</li>
								</ul>

								<div class="lzl_editor_container lzl_editor_container_s"
									style="display: none;">
									<div class="editor_for_container">
										<div class="lzl_simple_wrapper" style="width: 773px;">
											<textarea style="width: 767px;"></textarea>
										</div>
									</div>
									<table class="lzl_panel_wrapper">
										<tbody>
											<tr>
												<td style="width: 75%;"></td>
												<td style="width: 25%;">
													<div class="lzl_panel_btn">
														<span class="lzl_panel_submit">发表</span> <input
															type="hidden" class="replyToAuthor" value="" /> <input
															type="hidden" class="replyTo" value="" />
													</div>
												</td>
											</tr>
										</tbody>
									</table>
								</div>

							</div>
							<div class="core_reply_border_bottom"></div>
						</div>
<?php else : ?>
                        <div class="core_reply_tail">
							<div class="p_reply">
								<a class="lzl_link_unfold" href="###"
									style="display:; cursor: pointer">回复</a>
							</div>

							<ul class="p_tail">
								<li><span class=""><?php echo ($key + 2); ?>楼</span></li>
								<li><span><?php echo $floor['ctime'];?></span></li>
							</ul>
						</div>



						<div class="core_reply_wrapper" style="display: none;">
							<div class="core_reply_border_top"></div>
							<div class="core_reply_content" style="">
								<div class="lzl_editor_container lzl_editor_container_s"
									style="display: block;">
									<div class="editor_for_container">
										<div class="lzl_simple_wrapper"
											style="width: 773px; position: relative;">
											<textarea style="width: 767px;"></textarea>
										</div>
									</div>
									<table class="lzl_panel_wrapper">
										<tbody>
											<tr>
												<td style="width: 75%;"></td>
												<td style="width: 25%;">
													<div class="lzl_panel_btn">
														<span class="lzl_panel_submit">发表</span> <input
															type="hidden" class="replyToAuthor"
															value="<?php echo $floor['author'];?>" /> <input
															type="hidden" class="replyTo"
															value="<?php echo $floor['id'];?>" />
													</div>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<div class="core_reply_border_bottom"></div>
						</div>
<?php endif; ?>
</div>

				</div>
				<div class="clear"></div>
			</div>
<?php endforeach; ?>
</div>
		<div class="p_thread thread_theme_4" id="thread_theme_4">
			<div class="l_thread_info">
				<ul class="l_posts_num">
					<li class="l_pager pager_theme_3"></li>
					<li class="l_reply_num"
						style="margin-left: 2px; margin-right: 10px">共有<span class="red">1</span>页
					</li>
					<li class="l_reply_num"></li>
					<li class="l_reply_num">回复贴:<span class="red"
						style="margin-right: 3px">35</span></li>
				</ul>
			</div>
		</div>

	</div>
	<?php
echo $this->render('bbs/reply.phtml');
?>
</div>
<?php
echo $this->render('common/footer.phtml');
?>
<script data-main="/public/js/bbs.js"
	src="/public/js/lib/require-min.js"></script>
