<?php
echo $this->render('common/header.phtml');
?>
<?php
echo $this->render('common/menu.phtml');
?>
<div id="container"><!--content-->
	<div id="talk_content">
		<div id="talk_title" >
			<div class="gr_info r5">
				<h2>Gift 讨论吧</h2>无主题的主题吧，欢迎扎堆唠嗑。      
			</div>
		</div>
		<div id="talk_con">
			<div class="topic_filter">
				<div class="fl">
					<div class="filter_module">
						<b class="title">排序方式</b>
						<a href="#" class="selector">最新回应</a>
						<a href="#" class="selector ">最新创建</a>
						<a href="#" class="selector ">回复最多</a>
					</div>
				</div>
				<a href="write.html" class="newtopic_btn"></a>
          </div>
		</div>
	</div>

</div>
<?php
echo $this->render('common/footer.phtml');
?>