<?php
echo $this->render('common/header.phtml');
?>
<?php

echo $this->render('common/menu.phtml');
?>
<div id="container">
	<!--content-->
	<div id="talk_content">
		<div id="talk_title">
			<div class="gr_info r5">
				<h2>Gift 讨论吧</h2>
				无主题的主题吧，欢迎扎堆唠嗑。
			</div>
		</div>
		<div id="talk_con">
			<div class="topic_filter">
				<div class="fl">
					<div class="filter_module">
						<b class="title">排序方式</b> <a href="#" class="selector">最新回应</a> <a
							href="#" class="selector ">最新创建</a> <a href="#" class="selector ">回复最多</a>
					</div>
				</div>
				<a href="#new_topic" class="newtopic_btn"></a>
			</div>
		</div>
	</div>
	<div id="content_list">
		<ul class="threadlist">
		<?php foreach ($this->articles as $key => $article) :  
		          $title = $article->title; $likeTimes = $article->liked_times;
		          $table = Zend_Registry::get('dbtable')->user;
		?>
		<li class="<?php if ($key % 2 == 1) echo "threadlist_li_gray"; ?>">
				<div class="threadlist_li_left">
					<div title="<?php echo $likeTimes; ?>个赞" class="threadlist_rep_num"><?php echo $likeTimes; ?></div>
				</div>
				<div class="threadlist_li_right">
					<div class="threadlist_lz clearfix">
						<div class="threadlist_text threadlist_title notStarList ">
							<a href="/bbs/detail/aid/<?php echo $article->id;?>"
								title="<?php echo $title;?>" target="_blank"><?php echo $title;?></a>
						</div>
						<div class="threadlist_author" title="主题作者">
							<span class="tb_icon_author "><a class="sign_highlight"
								href="###"><?php echo $this->getUserInfo($article->author)[$table->username]; ?></a></span>
						</div>
					</div>
					<div class="threadlist_detail clearfix">
						<div class="threadlist_text">
							<div class="threadlist_abs threadlist_abs_onlyline"><?php echo $article->content; ?></div>
						</div>
						<div class="threadlist_author">
							<span class="tb_icon_author_rely" title="最后回复人"><a
								href="/i/sys/jump?un=%CF%FB%CA%C5%CC%EC%B1%DF%B5%C4%BB%D8%D2%E4"
								target="_blank"><?php echo $this->getUserInfo($article->last_reply_id)[$table->username]; ?></a></span> <span
								class="threadlist_reply_date" title="最后回复时间"><?php echo date('H:i', strtotime($article->mtime)); ?></span>
						</div>
					</div>
				</div>
				<div class="clear"></div>
			</li>
		<?php endforeach; ?>
	</ul>
	</div>
	<?php
    echo $this->render('bbs/post.phtml');
    ?>
</div>
<?php
echo $this->render('common/footer.phtml');
?>
<script data-main="/public/js/bbs.js"
	src="/public/js/lib/require-min.js"></script>
