<div id="container"><!--content-->
	<div id="talk_content">
		<div id="write_content">
			<div id="gr_set_top">
				<h2 id="new_topic" >发表主题</h2>
			</div>
			<div id="topic_con" class="gr_set_form ">
				<dl>
					<dt>标题：</dt>
					<dd>
                        <input class="form_text form_text_title" type="text" id="title" />
						<span class="desc"><b>最多25个字</b></span>
					</dd>
				</dl>
				<dl>
					<dt>正文：</dt>
					<dd>
					<textarea class="editor-textarea" id="article-content" style="height:250px;"></textarea>
						<span class="desc"></span>
					</dd>
				</dl>
				<dl class="sub_form" >
				<dt style="width: 75px;"></dt>
				<dd>
					<input type="button" class="form_sub mogu-editor-post" id="postArticle" value="发表" />
				</dd>
				</dl>
            </div>
			
		</div>
	</div>
</div>